# coding: utf-8
class CreateMakersModels < ActiveRecord::Migration
  def self.up
    Maker.create(:name=>"Allison".force_encoding('UTF-8'))
    m = Maker.find_by_name("Allison".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Alessandro Dell'Acqua".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Benetton".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Benetton Junior".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Bikkembergs".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Byblos".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Cerruti".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Dunhill".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Extè".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ferrè".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Frankie Morello".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Gf Ferrè".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Iceberg".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"John Richmond".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Les Copains".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Mercedes-Benz".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Missoni".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Moschino".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Roberta Di Camerino".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Romeo Gigli".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Trudi".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Try frames".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Try Change".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Zero RH+".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Westwood".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Sisley".force_encoding('UTF-8'))
    Maker.create(:name=>"Luxottica".force_encoding('UTF-8'))
    m = Maker.find_by_name("Luxottica".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Sferoflex".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Donna Karan".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Donna Karan New York".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ferragamo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Genny".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Persol".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Versace".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Versus".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Vogue".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Arnette".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Killer Loop".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Killer Loop Vista".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ray Ban".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ray Ban Vista".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ray Ban Junior".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ray Ban Vista Junior".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Revo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Prada".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Prada Linea Rossa".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Bulgari".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Burberry".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Chanel".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"D&G".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Dolce e Gabbana".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Miu Miu".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ralph Lauren".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Polo Ralph Lauren".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Purple Lable Ralph Lauren".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Mosley Tribes".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Oakley".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Oliver Peoples".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Anne Klein".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Brooks Brothers".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Chaps".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Club Monaco".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"DKNY".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Tiffany&co".force_encoding('UTF-8'))
    Maker.create(:name=>"Safilo".force_encoding('UTF-8'))
    m = Maker.find_by_name("Safilo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Alexander Mc Queen".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Blue Bay".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Hugo Boss".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Bottega Veneta".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Carrera".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"D 55".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Diesel".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Gucci".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Imatra".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Max Mara".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Oliver".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Oxydo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Pierre Cardin".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Polo Ralph Lauren".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Safilo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Smith Optics".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Stella Mc Carteney".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Valentino".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Yves Saint Laurent".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Emporio Armani".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Giorgio Armani".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Balenciaga".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Dior".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Marc Jacobs".force_encoding('UTF-8'))
    Maker.create(:name=>"Formelli".force_encoding('UTF-8'))
    m = Maker.find_by_name("Formelli".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Disney".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Harry Potter".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Vuarnet".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Bam'Boo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Principesse Disney".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Tabata".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Winnie The Pooh".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Fred".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Pro Design".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Tag Heuer".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Range Rover".force_encoding('UTF-8'))
    Maker.create(:name=>"Marcolin".force_encoding('UTF-8'))
    m = Maker.find_by_name("Marcolin".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Tom Ford".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Cebè".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ferrari".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Just Cavalli".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Miss Sixty".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Mont Blanc".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Replay".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Roberto Cavalli".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Web".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Timberland".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Covergirl".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Hogan".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"John Galliano".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Tod's".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Kenneth Kole".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Swarovski".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Dsquared²".force_encoding('UTF-8'))
    Maker.create(:name=>"Marchon Italia".force_encoding('UTF-8'))
    m = Maker.find_by_name("Marchon Italia".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Calvin Klein".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"CK".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Fendi".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Michael Kors".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Nike Vista".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Nike Flexon Sole".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Flexon Marchon".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Nike Sole".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Airlock".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Coach".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Emilio Pucci".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Jil Sander".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Karl Lagerfeld".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Nautica".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Sean John".force_encoding('UTF-8'))
    Maker.create(:name=>"Eurogriffe".force_encoding('UTF-8'))
    m = Maker.find_by_name("Eurogriffe".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Alpina".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Uvex".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Arquo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Egriffe".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Flash".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Yes".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Hql".force_encoding('UTF-8'))
    Maker.create(:name=>"Inottica".force_encoding('UTF-8'))
    m = Maker.find_by_name("Inottica".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Action Man".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Barbie".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Fischer Price".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Hot Wheels".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Pucca".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Seven".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Winx".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Transformers".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Hello Kitty".force_encoding('UTF-8'))
    Maker.create(:name=>"Cult ( EX A.P.F. Diffusion)".force_encoding('UTF-8'))
    m = Maker.find_by_name("Cult ( EX A.P.F. Diffusion)".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Alek Paul".force_encoding('UTF-8'))
    Maker.create(:name=>"Silhouette".force_encoding('UTF-8'))
    m = Maker.find_by_name("Silhouette".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Silhouette".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Adidas".force_encoding('UTF-8'))
    Maker.create(:name=>"Sover".force_encoding('UTF-8'))
    m = Maker.find_by_name("Sover".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Sover".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Baldnini".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Alviero Martini".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Mariella Burani".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Kiton".force_encoding('UTF-8'))
    Maker.create(:name=>"Vega".force_encoding('UTF-8'))
    m = Maker.find_by_name("Vega".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Façonnable".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Falir".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Koali".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Oga".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Seiko".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Vuillet Vega".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Zeiss".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Jaguar".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Lightec".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Nomad".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Rebel".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Yves Cogan".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Girard Perregaux".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Fabergè".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"St Dupont".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Stepper".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Carolina Herrera".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Custo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Marius Morel".force_encoding('UTF-8'))
    Maker.create(:name=>"Lepanto".force_encoding('UTF-8'))
    m = Maker.find_by_name("Lepanto".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Agatha Cruiz De La Prada".force_encoding('UTF-8'))
    Maker.create(:name=>"De Rigo".force_encoding('UTF-8'))
    m = Maker.find_by_name("De Rigo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Police".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Sting & Yamamay".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Lozza".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Jean Paul Gaultier".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Givenchy".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Chopard".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Furla".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Celine Lunettes".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Escada".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Etro".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Loewe".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ermenegildo Zegna".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Switch".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Tous".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Fila".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Pirelli".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Guess".force_encoding('UTF-8'))
    Maker.create(:name=>"Trevi Coliseum".force_encoding('UTF-8'))
    m = Maker.find_by_name("Trevi Coliseum".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Olivieri Studio".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Clark".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Cotton Club".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Coliseum".force_encoding('UTF-8'))
    Maker.create(:name=>"Visibilia".force_encoding('UTF-8'))
    m = Maker.find_by_name("Visibilia".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Blugirl".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Blumarine".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Emanuel Ungaro".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Jeckerson".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Laura Biagiotti".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Mandarina Duck".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"St. John".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Trussardi".force_encoding('UTF-8'))
    Maker.create(:name=>"GÖTTI".force_encoding('UTF-8'))
    m = Maker.find_by_name("GÖTTI".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Götti".force_encoding('UTF-8'))
    Maker.create(:name=>"POLARIS".force_encoding('UTF-8'))
    m = Maker.find_by_name("POLARIS".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Infinity".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"SP".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Twist".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Foxx".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Reava".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Mixx".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Onyx".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Staffan Preutz".force_encoding('UTF-8'))
    Maker.create(:name=>"LINDBERG".force_encoding('UTF-8'))
    m = Maker.find_by_name("LINDBERG".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Spirit".force_encoding('UTF-8'))
    Maker.create(:name=>"KYO YAMATO".force_encoding('UTF-8'))
    m = Maker.find_by_name("KYO YAMATO".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Kyo Yamato Titanium".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"O & X New York".force_encoding('UTF-8'))
    Maker.create(:name=>"MIKLI".force_encoding('UTF-8'))
    m = Maker.find_by_name("MIKLI".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Alain Miklì".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Starck Eyes".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"m/m".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Issey Miyake".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Sara Eliris".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Marco Salgado".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Bless".force_encoding('UTF-8'))
    Maker.create(:name=>"ZIO EYEWEAR".force_encoding('UTF-8'))
    m = Maker.find_by_name("ZIO EYEWEAR".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Zio".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Mini Zio".force_encoding('UTF-8'))
    Maker.create(:name=>"OCCHIALI FAMOSI".force_encoding('UTF-8'))
    m = Maker.find_by_name("OCCHIALI FAMOSI".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Histoire De Voir".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Gold & Wood".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Kirk".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"ByWP".force_encoding('UTF-8'))
    Maker.create(:name=>"MATI'S".force_encoding('UTF-8'))
    m = Maker.find_by_name("MATI'S".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Bellinger".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Kamaeleon".force_encoding('UTF-8'))
    Maker.create(:name=>"EYEWORKS 3".force_encoding('UTF-8'))
    m = Maker.find_by_name("EYEWORKS 3".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"L.A. Eyeworks".force_encoding('UTF-8'))
    Maker.create(:name=>"REME".force_encoding('UTF-8'))
    m = Maker.find_by_name("REME".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Lafont".force_encoding('UTF-8'))
    Maker.create(:name=>"ANNE ET VALENTIN".force_encoding('UTF-8'))
    m = Maker.find_by_name("ANNE ET VALENTIN".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Anne Et Valentin".force_encoding('UTF-8'))
    Maker.create(:name=>"EM EYEWEAR".force_encoding('UTF-8'))
    m = Maker.find_by_name("EM EYEWEAR".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Em Eyewear".force_encoding('UTF-8'))
    Maker.create(:name=>"ELITE GROUP".force_encoding('UTF-8'))
    m = Maker.find_by_name("ELITE GROUP".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Elite Group".force_encoding('UTF-8'))
    Maker.create(:name=>"INTERNATIONAL DESIGN CREATION".force_encoding('UTF-8'))
    m = Maker.find_by_name("INTERNATIONAL DESIGN CREATION".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Idc".force_encoding('UTF-8'))
    Maker.create(:name=>"IC! BERLIN".force_encoding('UTF-8'))
    m = Maker.find_by_name("IC! BERLIN".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Ic Berlin".force_encoding('UTF-8'))
    Maker.create(:name=>"ETNIA BARCELONA".force_encoding('UTF-8'))
    m = Maker.find_by_name("ETNIA BARCELONA".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Etnia".force_encoding('UTF-8'))
    Maker.create(:name=>"MARKUS T".force_encoding('UTF-8'))
    m = Maker.find_by_name("MARKUS T".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Markus t".force_encoding('UTF-8'))
    Maker.create(:name=>"ITALIA IDEPENDENT".force_encoding('UTF-8'))
    m = Maker.find_by_name("ITALIA IDEPENDENT".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Italia Independent".force_encoding('UTF-8'))
    Maker.create(:name=>"VIVIENNE WESTWOOD".force_encoding('UTF-8'))
    m = Maker.find_by_name("VIVIENNE WESTWOOD".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Vivienne WestWood".force_encoding('UTF-8'))
    Maker.create(:name=>"ITALIAN STYLE".force_encoding('UTF-8'))
    m = Maker.find_by_name("ITALIAN STYLE".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Nouvelle Vague".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Paolo Seminara".force_encoding('UTF-8'))
    Maker.create(:name=>"EYEWEAR DESIGNS LTD.".force_encoding('UTF-8'))
    m = Maker.find_by_name("EYEWEAR DESIGNS LTD.".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Perry Ellis".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Elizabeth Arden".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Levi's".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Jill Stuart".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"New Balance".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Donald J Trump".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Bill Blass".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Scooby-Do!".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Hershey's".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Apple Bottoms".force_encoding('UTF-8'))
    Maker.create(:name=>"JAI KUDO".force_encoding('UTF-8'))
    m = Maker.find_by_name("JAI KUDO".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Jai Kudo".force_encoding('UTF-8'))
    Maker.create(:name=>"ESCHENBACH".force_encoding('UTF-8'))
    m = Maker.find_by_name("ESCHENBACH".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"TITANflex".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Humphrey's".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Marc O'Polo".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Bogner".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Brendel".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Fineline".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Crush".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"Oio".force_encoding('UTF-8'))
    Maker.create(:name=>"FRANÇOIS PINTON".force_encoding('UTF-8'))
    m = Maker.find_by_name("FRANÇOIS PINTON".force_encoding('UTF-8'))
    Model.create(:maker_id => m.id, :name =>"François Pinton".force_encoding('UTF-8'))
    
    Maker.find(:all).each do |m|
      m.update_attribute(:name, m.name.titleize)
    end
    
  end
  def self.down
  end
end
